from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from typing import List

from app.db.database import get_db
from app.models.product import Product
from app.schemas.product import ProductCreate, ProductResponse

# Create a router instance for products
router = APIRouter(prefix="/products", tags=["Products"])

@router.post("/", response_model=ProductResponse, status_code=status.HTTP_201_CREATED)
def create_product(product: ProductCreate, db: Session = Depends(get_db)):
    """
    Add a new product to the inventory.
    """
    # 1. Convert Pydantic schema to SQLAlchemy model
    db_product = Product(**product.model_dump())
    
    # 2. Add to database session and save
    db.add(db_product)
    db.commit()
    db.refresh(db_product) # Get the new ID generated by the database
    
    return db_product

@router.get("/", response_model=List[ProductResponse])
def get_products(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    """
    Retrieve a list of all products in inventory.
    """
    products = db.query(Product).offset(skip).limit(limit).all()
    return products